package controller;

public enum Actions {

	SHOW_SIGN_IN_PANEL,SHOW_LOGIN_IN_PANEL,RENDITION,
        LOGIN, LOG_OUT,CUSTOM_GAME,CLASIC_GAME,CREATE_PLAYER,SHIP_PRESSED, CREATE_CUSTOM_GAME, SHOW_BEST_PLAYERS, SING_IN;
	
}
